defaults: &defaults
  allow_dynamic_fields: false
  identity_map_enabled: false
  use_activesupport_time_zone: true
  preload_models: true


development:
  host: localhost
  database: directory_app_development

test:
  host: localhost
  database: directory_app_test

# set these environment variables on your prod server
production: &production
  <<: *defaults
  uri: <%= ENV['MONGOLAB_URI'] %>
